### ISSUE TITLE
Upgrade which dependency

### ISSUE THREAD

**Issue by oliversalzburg** [timoxley/npm-path#1]
The version of `which` that is being used in this library, has a bug:

``` js
  // On windows, env.Path is common.
  if (isWindows && !pathEnv) {
    var k = Object.keys(process.env)
    for (var p = 0; p < k.length; p++) {
      if (p.toLowerCase() === 'path') {
        pathEnv = process.env[p]
        break
      }
    }
  }
```

`p` is a number and not a string. Thus, this library doesn't work on Windows.

**Comment by timoxley** [comment]
``` json
"dependencies": {
    "which": "^1.0.5"
}
```

The `^1.0.5` should mean that npm will install `which@1.1.1` for you. I'll bump the minimum dep but you probably just need to do a clean `npm install`

**Comment by oliversalzburg** [comment]
@timoxley Huh, I guess you're right. I don't know why I had an older version. My guess is that another module depended on `1.0.5` specifically and that was higher up in the dependency graph, so it was used.
