### ISSUE TITLE
Remove duplicated PATH entries

### ISSUE THREAD

**Issue by piranna** [timoxley/npm-path#4]
I've found that `npm-path` unshift its entries at beginning ot the `$PATH` variable, and since it adds the location of the currently used `node` binary, that location it's shown twice, and probably the same with the others. The same happens if you exec the `npmPath()` function several times, that the `$PATH` gets increasing.

I suggest that previously to set/return the `$PATH` filter the duplicated latest ones, since they would be used before when looking on the paths added by `npm-path`. This would need to record the original `$PATH` somewhere and apply the changes to it each time it's executed, but also having it available would be useful in some use cases...

**Comment by timoxley** [comment]
Closed in #5
